### ISSUE TITLE
hellen72 document tach/alternator 5v as 12v

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#10]
![image](https://user-images.githubusercontent.com/48498823/116311301-1c24fe80-a779-11eb-9ef2-7455ab1fed1d.png)

**Comment by BeerMoneyMotorsports** [comment]
do you have more details on this?  what revision?  Tach functionality is not an issue on NB2 rev D.

**Comment by rusefillc** [comment]
Looks like no need for anything here
