### ISSUE TITLE
remove M9

### ISSUE THREAD

**Issue by mck1117** [rusefi/hellen-NB2-issues#14]
why do we have LIN/K-line at all?

It's extra hardware we don't use.  Adds cost.  Opportunities for BOM mistakes, as we've seen where somehow https://github.com/rusefi/hellen72/blob/master/boards/hellen72-d/board/hellen72-d-BOM.22september2021.csv contains a TJA10*5*1 in place of a TJA10*2*1.

**Comment by BeerMoneyMotorsports** [comment]
LIN is removed from rev E.
