### ISSUE TITLE
144 mcu analysis

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#18]
would 144 be a drop-in replacement or would it change stm32 pinout?

**Comment by BeerMoneyMotorsports** [comment]
rev E utilizes 144pin MCU.  STM32f407zgt7

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports that would require two different yaml files or some other software provisions. Board ID hardware could be helpful to facilitate options on software side

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc with such a drastic change, it may be good to just break the chain and create new yaml?  I will need your expertise to devise and good solution.  

Currently, per my direction, the NB2 rev E is a copy of NB1 design with updated pinouts.  it seemed to be the simplest solution but I clearly did not take into account the difference in chips effect on firmware.  

Can we make NB2 rev D an end of life and rev E starts a new generation?

**Comment by rusefillc** [comment]
do we kill old NB2 binaries and not support old NB2 hardware?
do we kill old NB2 page?
do we somehow mix old and new help content on same wiki page?

I am totally fine adding new yaml file but that would be a lot of hard work here and there to make this mess less confusing

board-id stuff was never fabricated so far but I hope there are no down sides to having it on the boards https://github.com/andreika-git/hellen-one/issues/105 https://github.com/rusefi/hellen128merc-issues/issues/38 in order at least to attempt fancy approach

**Comment by BeerMoneyMotorsports** [comment]
The decision was made to maintain 176 pin chip for NB2.  I have purchased 40 for my personal stock at JLCPCB.   Closing the issue.
