### ISSUE TITLE
94 pin connector - tracking stock, nothing else

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#19]
We can purchase the 94pos but things are a bit iffy

I have qty 6 I would love to sell to "anyone" fabricating a board with 94pos connector @BeerMoneyMotorsports wink wink

https://octopart.com/search?q=1123794&currency=USD&specs=0

It would have been amazing if we had a source of used as a backup now that I have my fancy ultrasonic bath. Problem is I am not aware of ANY ecu using this 94pos. https://github.com/rusefi/rusefi/wiki/OEM-connectors#94-pin

![image](https://user-images.githubusercontent.com/48498823/134385001-6258f4d8-ba0c-47e2-909b-e2c689ed4b47.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports 

![image](https://user-images.githubusercontent.com/48498823/141032343-fc1b51cd-6bc2-449a-85f6-58734dd94002.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports friendly reminder that only 6 are for sale on the market and I have only 6, grand total of 12.

**Comment by BeerMoneyMotorsports** [comment]
I need to validate if this is available option or not.  

![image](https://user-images.githubusercontent.com/82395131/147261059-e7b189e3-e12c-4a2d-9497-c6ded984a37b.png)

**Comment by rusefillc** [comment]
125 pin honda K is available from China https://www.ebay.com/itm/334141525131

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc looks like it may be a touch too big for our application.  I wonder if we can reasonably cut down the K connector to be 94pin?

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc also, what resource in china for the honda K?

**Comment by BeerMoneyMotorsports** [comment]
closing as we have moved from 94-122 pin.
