### ISSUE TITLE
vvt target table

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#22]
we have an aggressive table and we need to set it more like other known good tables.

ours
![image](https://user-images.githubusercontent.com/82395131/139967056-0536985a-da6f-4deb-8d78-491636b87d46.png)

other known good
![image](https://user-images.githubusercontent.com/82395131/139967217-22920868-0b9c-412c-890f-03e853542965.png)

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports can you please post a rusEFI online tune URL since that's the only thing I can import into defaults directly?

**Comment by BeerMoneyMotorsports** [comment]
![image](https://user-images.githubusercontent.com/82395131/140003240-e5cfc1af-3002-4bd5-8a52-4e0d4a08e3bc.png)

**Comment by BeerMoneyMotorsports** [comment]
Closing.
