### ISSUE TITLE
Pin Error While driving around TC4427 maybe alternator damage in USA

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#23]
https://rusefi.com/forum/viewtopic.php?f=19&t=2190

Related to https://github.com/rusefi/hellen-NB1-issues/issues/25

shipping Matthew Kennedy the failed board via usps for inspection.

**Comment by BeerMoneyMotorsports** [comment]
![Uploading D5CA99E5-127B-4D83-965C-272CF82FEF98.jpeg…]()

**Comment by rusefillc** [comment]
Some relevant notes on https://github.com/rusefi/rusefi/issues/3558
There is an opinion that we need https://github.com/andreika-git/hellen-one/issues/118

**Comment by mck1117** [comment]
I have the board in-hand now.

Notes:

- The STM32 gets hot when power is applied, but at least the core seems to still work, as TS connects and works (at least until it gets super hot and things stop working)
- Those pins that go to the TC4427 have 8-10 ohms to ground, and one of them has 2 ohms to the 3.3v rail, indicating catastrophic failures of the rail steering diodes (or possibly output transistors), and the other has ~20 ohms to the 3.3v rail.  

I'm not sure how that happened, but a 1k series resistor (optionally a pulldown too for safety) would likely prevent it by avoiding whatever overcurrent condition caused the steering diodes to fuse.

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 thank you.  Can you Write a ticket for us to add the resistor to future boards?  I need to order nb1 immediately. Is it too soon to make this call while you are still diagnosing everything?

Do we need to find a way to add this to current boards in customer hands?

**Comment by mck1117** [comment]
is this not that ticket? https://github.com/andreika-git/hellen-one/issues/118

**Comment by mck1117** [comment]
It will certainly not hurt.  Many proteus/mre/frankenso boards have been driving around with those resistors in place.

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 thankyou. Sorry I overlooked the ticket.

**Comment by mck1117** [comment]
Actually I take that back - Proteus/MRE have pulldown resistors on the input side, but no series resistor.  They do, however, have a resistor on the output, also absent from Hellen.

**Comment by BeerMoneyMotorsports** [comment]
Per @mck1117 reverse engineering OEM ecu.  He found a 1k resistor in series and a 100nf to gnd.  Picture below to show circuit.  This is being added to NB1 production.  NB2 is being tested with updated circuit.

![image](https://user-images.githubusercontent.com/82395131/144648122-5655269c-c44a-4105-9ee0-d51a3f76f307.png)

related ticket-  https://github.com/rusefi/hellen-NB1-issues/issues/25

**Comment by BeerMoneyMotorsports** [comment]
Modified board to test.

@mck1117 or @andreika-git , i would need some help with how to torture testing NB2.  

![nb2 alt mod](https://user-images.githubusercontent.com/82395131/144649010-33847ac8-a9ee-4fdd-a2a8-0f9c7d06c336.jpg)

**Comment by BeerMoneyMotorsports** [comment]
Board was tested for 250 miles then returned to the customer for further testing.  No failures during my testing which mainly consisted of lots of idling and driving.  This is with AC, lights, wipers, etc all running.

**Comment by BeerMoneyMotorsports** [comment]
This board has 750 miles on it with zero problems.  Fix has been applied to rev nb2 rev E and then NB1 rev B.  Miata NA does not have alternator control circuit.  so 90-95 and 96/97 will have the 0.3 output module with protection but not a specific alternator control circuit.
