### ISSUE TITLE
94 pin connector - row pitch conflict (footprint vs 3d-model)

### ISSUE THREAD

**Issue by andreika-git** [rusefi/hellen-NB2-issues#26]
We have two options for the 94 pin connector: 1473181-1 and 1123794-2. 
According to the datasheet, both have the same row pitch as the 72 pin connector had:
![image](https://user-images.githubusercontent.com/15104768/146386370-e3c58dfe-768f-407b-9563-02700c79a9f2.png)
The problem is that the 3D models given by the manufacturer don't match the footprint because they have different row pitch (2.5 mm):
![image](https://user-images.githubusercontent.com/15104768/146387210-44e89bb9-f63c-4bd3-ae84-43a18e62070a.png)

@BeerMoneyMotorsports Can you please measure the distance between the rows (of the pcb pins) on a real 94 pin connector? Is it 3.6mm+4.4mm or 2.5mm+2.5mm?

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc do you have a 96pin connector you can measure?  i have not purchased any yet.

**Comment by rusefillc** [comment]
@BeerMoneyMotorsports @andreika-git I have a connector in my hands its 3.6mm+4.4mm

**Comment by BeerMoneyMotorsports** [comment]
closing as we have moved from 94-122 pin.
