### ISSUE TITLE
Convert to 122 pin header

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#28]
Lack of stock on 94 pin connector is forcing us to use the next size up, 122 pin connector.  It is a perfect fit for the camry case.

![image](https://user-images.githubusercontent.com/82395131/147370926-614da345-f307-4ed3-8213-337d5547be8c.png)

https://www.te.com/usa-en/product-8-5353015-1.html

**Comment by andreika-git** [comment]
We need to know the exact position of the connector on board.

**Comment by rusefillc** [comment]
nice find!

https://octopart.com/search?q=5353015&currency=USD&specs=0

![image](https://user-images.githubusercontent.com/48498823/147371030-fb881230-d397-4067-bfc0-8456dd1f1736.png)

**Comment by BeerMoneyMotorsports** [comment]
Centered, connector in pic below is the same as 122 pin.

![image](https://user-images.githubusercontent.com/82395131/147371265-0ab3b3b0-c0af-42e7-8448-7a00e9e761ca.png)

**Comment by andreika-git** [comment]
Can you please measure the distance between the outer mounting points?
![image](https://user-images.githubusercontent.com/15104768/147381706-80484002-1e93-4ee7-8dfc-e5d55683bd4f.png)

The is a misalignment between the official 3D model and the footprint (based on the datasheet):
![image](https://user-images.githubusercontent.com/15104768/147381754-4bb24d66-2d40-45ff-b0d3-ab811da80998.png)

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git i am measuring 111.1mm

**Comment by BeerMoneyMotorsports** [comment]
closing.  completed with REV E
