### ISSUE TITLE
Q1, Q2 footprint revision

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#34]
Q1 and Q2 should have a footprint that allows both the AUIPS2041LTR and ZXMS6005SGTA chips.  Currently it does not, as the Tab on the chip is being used.  The AUIPS2041LTR and ZXMS6005SGTA do not have compatible footprints if the Tab is being used.  AUIPS2041LTR connects pin 2 to Tab and ZXMS6005SGTA connects pin 3 to Tab.  

<img width="368" alt="image" src="https://user-images.githubusercontent.com/82395131/160432573-3ada70f6-5e12-4923-a5bc-0fb2a7d1d4ff.png">

**Comment by rusefillc** [comment]
See also https://github.com/andreika-git/hellen-one/issues/147

**Comment by andreika-git** [comment]
done (for the next rev.F)
![image](https://user-images.githubusercontent.com/15104768/160442543-9de4f3b6-964a-4514-8487-73b8ab05ee46.png)

**Comment by BeerMoneyMotorsports** [comment]
Either rev F needs to be released now or this fix needs to be applied to Rev E.  AUIPS2041 is unavailable in my searches.  The only availability is ZXMS6005SGTA.  I have just enough AUIPS2041 for the 5 NB2e i have in hand but will not be able to produce any after that.

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git this is one that needs urgent attention.

**Comment by BeerMoneyMotorsports** [comment]
fixed with F
