### ISSUE TITLE
Hellen Board ID

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#37]
NB2c
<img width="317" alt="image" src="https://user-images.githubusercontent.com/82395131/176568089-e15233b8-cc78-48cf-a034-9ead9cdd6d3c.png">

NB2d
<img width="347" alt="image" src="https://user-images.githubusercontent.com/82395131/176566739-1e50c001-98b8-40e0-8906-4f567f91fcb1.png">

NB2f
<img width="335" alt="image" src="https://user-images.githubusercontent.com/82395131/176567632-9a37fac2-1840-447b-b926-4389f90ecacf.png">

**Comment by rusefillc** [comment]
thank you! looks good.

do you have 'E'?
@andreika-git FYI we have '1' offset for 'unknow' and '0' means 'hellen id not invoked'

**Comment by BeerMoneyMotorsports** [comment]
I do not have E on hand.

**Comment by rusefillc** [comment]
Looks great!
