### ISSUE TITLE
Injector Drivers NCV8440ASTT3G

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#38]
I have validated that the below drivers work.  I have them on a Hellen NB2 revF in my personal car.  It runs very well.  I am unsure how these technically compare to the current drivers.  

Mouser #:	[863-NCV8440ASTT3G](https://www.mouser.com/ProductDetail/863-NCV8440ASTT3G)
Mfr. #:	NCV8440ASTT3G
Desc.:	MOSFET MOSFET 2.6A, 52V N-CH, CLAM

**Comment by rusefillc** [comment]
I've just filled in part request to have JLC stock those

![image](https://user-images.githubusercontent.com/48498823/180655637-028d2011-1652-46f1-8301-e6b4aeca4188.png)

**Comment by rusefillc** [comment]
they have added $1 to the price

![image](https://user-images.githubusercontent.com/48498823/180733381-d008b13d-a011-433a-b186-a24825c2528e.png)
