### ISSUE TITLE
176 availability

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#39]
C33993

not great at all but kind of manageable just to survive the next two months?

![image](https://user-images.githubusercontent.com/48498823/176994380-068a0602-3b4b-4d8d-961a-6f4afcae37e1.png)

more history at https://github.com/andreika-git/hellen-one/issues/19

**Comment by BeerMoneyMotorsports** [comment]
Manageable but not wonderful.
