### ISSUE TITLE
Trigger sync issue NB2

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#42]
Car- NB2
ECU- Hellen 72 rev D
New Firmware- 8/12/22 release
Old Firmware- 4/22/2022

Customer reports that he is hitting a "rev limit" at 6500 rpm and TS shows Trigger Sync issue.  This occurred after updating firmware and no tune changes. 

Here is the log: https://rusefi.com/online/view.php?log=989
Tune: https://rusefi.com/online/view.php?msq=1174

**Comment by rusefillc** [comment]
Can he go back current or prev release?

**Comment by BeerMoneyMotorsports** [comment]
He can go back to the 4/22 release if needed for testing.

**Comment by rusefillc** [comment]
yes, please test again with https://github.com/rusefi/rusefi/releases/tag/20220812_release and https://github.com/rusefi/rusefi/releases/tag/20220702_release

**Comment by BeerMoneyMotorsports** [comment]
Sebastian tried firmware 20220702 last night with same result.  Tonight he will try older.

**Comment by BeerMoneyMotorsports** [comment]
Looks like this was a case of coincidence.  He double checked some things to make sure and found a failing cam sensor.  replaced and all is well with 8,12 firmware.
