### ISSUE TITLE
RZ7899 out of stock

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellen-NB2-issues#43]
It has been a while since i have placed an order due to very low sales.  Looks like U300/303 are not available.  These are used on the miata boards.  I do not see any Motor Driver ICs in SOP-8 available and i do not know what a reasonable replacement would be from another resource.

**Comment by andreika-git** [comment]
Unfortunately, there's no direct replacement for RZ7899...

**Comment by BeerMoneyMotorsports** [comment]
welp, that kinda kills us.

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git do you have any desire to redesign the output module?

**Comment by BeerMoneyMotorsports** [comment]
still no stock.  hellen is dead without a redesign.
