### ISSUE TITLE
Two rev D boards would not go into software DFU

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#5]
Two out of two rev D boards I have would not jump into SW DFU

HW DFU works fine (both power on with PROG and reset under PROG)
SW DFU just reboots the board into without not DFU mode - i.e. we loose USB connection, we change blue blinking frequency but we keep bilking blue

@BeerMoneyMotorsports has the other three rev D boards in the mail so he would confirm on his end
hopefully @BeerMoneyMotorsports has a rev C to compare

**Comment by BeerMoneyMotorsports** [comment]
@rusefillc i have rev C to compare

**Comment by rusefillc** [comment]
i run experimenters with https://github.com/rusefi/rusefi/releases/tag/2021.06.28_release

i think _once_ it has rebooted into DFU but only once.

so it seems sporadic? maybe some power supply drama?

**Comment by andreika-git** [comment]
Can you please make a close-up photo of the STM32 soldered on the board? We need to compare the chip labels with rev.C

**Comment by mck1117** [comment]
I've just tried on a Rev A hellen 121 and it rebooted back to the firmware, not DFU

**Comment by rusefillc** [comment]
@mck1117 welcome to the party!!! what about 121-vag-B?

@andreika-git any chance you can try Hellen-72 A or B you have?

**Comment by rusefillc** [comment]
@andreika-git @mck1117 

H72-C is F429IIT6
H72-D is F407IGT6

**Comment by mck1117** [comment]
I have just flashed `snapshot_20210628_214332_hellen121vag_rusefi` on an old Proteus 0.4 of August 2020 vintage, and "reset to DFU" button WORKED

**Comment by rusefillc** [comment]
I wonder if there is a correlation or causation between exact CPU model and this issue

Which F4xx is Rev A hellen 121 vag?
Which F4xx is Rev B hellen 121 vag and how does it vote?
Which F4xx is old Proteus 0.4?

**Comment by andreika-git** [comment]
> @andreika-git any chance you can try Hellen-72 A or B you have?
SW DFU works on H72b

**Comment by rusefillc** [comment]
So one would suspect 407 right?

I've just tested with a small old DISCOVERY 407 and SW DFU works just fine? so 100 pin 407 is happy and 176 407 is not?

**Comment by rusefillc** [comment]
@mck1117 could this be about power supply? especially my sporadic one time good reboot

maybe I shall add AP2337 tomorrow?

**Comment by andreika-git** [comment]
Also you can try with an external +12V power

**Comment by rusefillc** [comment]
@andreika-git is in the lead - rev D enters SW DFU as long as powered by +12v

**Comment by mck1117** [comment]
It happens if connected to an actual USB host, but not if connected to USB power (usb power bank battery)

**Comment by mck1117** [comment]
I've just tested with 12v connected, and it DID NOT HELP

**Comment by rusefillc** [comment]
I've added one AP2337 to MCU module that made zero difference

I am not 100% but it looks like PROG holding + RESET does NOT always get me DFU only MOST of the time?! Need to made a video

**Comment by mck1117** [comment]
I see the same thing, button is not 100% reliable either

**Comment by rusefillc** [comment]
https://community.st.com/s/question/0D53W00000wyoGESAY/sporadic-reset-into-dfu-and-dfu-jump-any-links-between-power-and-dfu

**Comment by rusefillc** [comment]
Matthew Kennedy  10:29 PM
I did some probing

The dfu software is running, then resetting after ~800us

Before the oscillator initializes

But it didn't even try the osc

![image](https://user-images.githubusercontent.com/48498823/125183642-487fe100-e1e6-11eb-964a-1ad8670c4791.png)

**Comment by rusefillc** [comment]
https://github.com/rusefi/hellen121vag/issues/50 was done while investigating this issue

**Comment by mck1117** [comment]
Observation 1: powering from 12v (no USB connected), BOOT0 button is 100% reliable
Observation 2: powering from 5v USB power bank (no 12v, but also no data lines), BOOT0 button is 100% reliable.  Test performed with the same cable that is unreliable with laptop.
∴ the problem is not power, but is USB data lines.

**Comment by mck1117** [comment]
H72B is 100% reliable with F427IGT6

**Comment by mck1117** [comment]
Took the chip from the working H72B, put it on an H121B board.  Works perfectly.

**Comment by mck1117** [comment]
DFU ROM matches, except for the odd duck that's a very old ST F4 discovery board:

![image](https://user-images.githubusercontent.com/568254/125186098-377ea200-e1dd-11eb-802e-6023b06b05c1.png)

**Comment by rusefillc** [comment]
I've shared the drama with @dron0gus 

Dron says 407 has one VCAP while 42x have two VCAP or something? i like this line of inquiry

**Comment by rusefillc** [comment]
With VAG and NA6 reports this is now https://github.com/andreika-git/hellen-one/issues/79
