### ISSUE TITLE
Rev C board plugged into real vehicle with both 2002 and 2003 jumpers. How bad is it?

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#6]
I had board running/plugged into 2003 vehicle with both jumpers what's the level of potential damage if any?

**Comment by andreika-git** [comment]
It's equal to 4S and 4T pins shorted. Needs investigation depending on vehicle type...

**Comment by rusefillc** [comment]
original description updated with details on vehicle

**Comment by BeerMoneyMotorsports** [comment]
both jumpers installed should not cause damage.  you should notice a lack of VVT control.
