### ISSUE TITLE
gap analysis between hellen72 and mazda speed miata

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen-NB2-issues#9]
looks like mazdaspeed miata uses 72 pin connector and we kind of forgot about it?

https://github.com/rusefi/rusefi/wiki/Mazdaspeed-Miata-2005

**Comment by mck1117** [comment]
IIRC there's a boost control solenoid somewhere in lieu of VVT.

**Comment by BeerMoneyMotorsports** [comment]
https://docs.google.com/spreadsheets/d/1raHTEK5JAHUCpqOJ4ms5ALVBcwi8FxiH_gkN7S6F6c4/edit#gid=0
